### @host = http://localhost:8080/matchboxv3/fhir
@host = https://test.ahdis.ch/matchbox/fhir



### Convert FML to StructureMap and and PUT on server
PUT {{host}}/StructureMap/HIVObservationHIVCondition HTTP/1.1
Content-Type: text/fhir-mapping
Accept: application/fhir+json

< ./HIVObservationHIVCondition.map


### Transforms 1
POST {{host}}/StructureMap/$transform?source=https://path-global-health.github.io/MERindicators/StructureMap/HIVObservationHIVCondition
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0
 
< ./test_data/3e990510-1d51-4a25-abd4-3885cf9e8be9.json

###>>! ./transforms/3e990510-1d51-4a25-abd4-3885cf9e8be9.json


### Transforms 2
POST {{host}}/StructureMap/$transform?source=https://path-global-health.github.io/MERindicators/StructureMap/HIVObservationHIVCondition
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0
 
< ./test_data/445beebb-e886-11ea-87c2-00155d017200.json

>>! ./transforms/445beebb-e886-11ea-87c2-00155d017200.json


### Transforms 3
POST {{host}}/StructureMap/$transform?source=https://path-global-health.github.io/MERindicators/StructureMap/HIVObservationHIVCondition
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0
 
< ./test_data/e70e0b6a-f2a2-4a5a-af3c-dbe08925d01e.json

>>! ./transforms/e70e0b6a-f2a2-4a5a-af3c-dbe08925d01e.json

### Transforms 3
POST {{host}}/StructureMap/$transform?source=https://path-global-health.github.io/MERindicators/StructureMap/HIVObservationHIVCondition
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0
 
< ./test_data/0a2f4c9b-0963-4ea6-8d8c-da9b461460d1/0a2f4c9b-0963-4ea6-8d8c-da9b461460d1.json